# Generated by Django 5.0.2 on 2024-03-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subtitle',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
