# Generated by Django 5.0.2 on 2024-03-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_article_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
